server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  port: 8080

spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/veterinary
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

